### PR TITLE
Change name to repoze-lru for pip 8 resolution

### PR DESCRIPTION
**Pull request by khornberg**

### CODE REVIEW

**Comment by khornberg** [comment]
I'm not sure if other things in `setup.cfg` need to be changed or not.

**Comment by tseaver** [comment]
I don't understand the motivation: this package:  pip has no trouble installing the package as is.

**Comment by khornberg** [comment]
Installing from `pypi.org` works because they have generously converted the `.` to a `-` e.g. `https://pypi.org/simple/repoze.lru/` is redirected to/resolved as `https://pypi.org/simple/repoze-lru/`

In my case, I am not installing `repose.lru` from pypi.org but from a self hosted pypi server that does not do that conversion for me.

**Comment by tseaver** [comment]
@khornberg Thanks for your efforts, but I'm going to have to decline the change.  The "normailization" from `repoze.lru` -> `repoze-lru` is an artifact of a (dubious) implementation choice made by the PyPA.  The *actual* name of this project is `repoze.lru`.

**Pull request closed without merging**
